In [1]:
import numpy as np

a = ([1,2,3,4])
np.array (a)

array([1, 2, 3, 4])

In [2]:
np.array ([(1,2,3,4), (5,6,7,8), (9,10,11,12)])

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [3]:
np.array ([[(1,2,3), (4,5,6)], [(7,8,9), (10,11,12)]])

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [4]:
a= ([1,2,3])
b= ([4,5,6])
np.add (a,b)

array([5, 7, 9])

In [5]:
a = ([16, 36, 64])
np.sqrt(a)

array([4., 6., 8.])

In [6]:
a= [(10)]
np.log(a)


array([2.30258509])

In [7]:
np.sin(a)

array([-0.54402111])

In [8]:
np.ones([4,5])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [9]:
# array of evenly space values (start, end, step value). End value not inclusive in the array.
np.arange (2, 10, 2)

array([2, 4, 6, 8])

In [74]:
# array of evenly spaced values (start, end, step value). End value is inclusice in the array.
np.linspace (2, 10, 5)

array([ 2.,  4.,  6.,  8., 10.])

In [11]:
np.full ((3,2), (9,10))

array([[ 9, 10],
       [ 9, 10],
       [ 9, 10]])

In [12]:
np.full (2,9)

array([9, 9])

In [13]:
# Identity Matrix 
np.eye (5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [14]:
# create an array of random value
np.random.random ((2,2))

array([[0.23329186, 0.30757732],
       [0.20834996, 0.46197129]])

In [15]:
np.random.ranf (2)

array([0.30963714, 0.78727675])

In [16]:
np.empty ((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [17]:
np.zeros ((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [18]:
a = ([2,4,6])
b = ([2,4,6])

np.array_equal(a,b)

True

In [75]:
# Shape of array
y = np.array ([(1,2,3), (4,5,6), (7,8,9)])
np.shape (y)

(3, 3)

In [20]:
# length of array
len (y)

3

In [21]:
# dimension of array
y.ndim

2

In [22]:
# number of elements in array
y.size

9

In [23]:
# Data type of array element
y.dtype

dtype('int64')

In [24]:
# converty array to in int type
y.astype(int)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [25]:
y.astype(float)

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [26]:
y.min()

# maximum value among all rows
y.max(axis = 0)

array([7, 8, 9])

In [27]:
# maximum values among all columns
y.max (axis=1)

array([3, 6, 9])

In [28]:
# sum of elements 
y.cumsum (axis=0)

array([[ 1,  2,  3],
       [ 5,  7,  9],
       [12, 15, 18]])

In [29]:
y.cumsum(axis=1)

array([[ 1,  3,  6],
       [ 4,  9, 15],
       [ 7, 15, 24]])

In [30]:
y.mean()

5.0

In [31]:
# standard deviation
np.std(y)

2.581988897471611

In [32]:
np.copy(y)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [33]:
h= y.copy
h

<function ndarray.copy>

In [35]:
y = np.array ([(1,2,3), (7,8,9), (4,5,6)])
y.sort()
y

array([[1, 2, 3],
       [7, 8, 9],
       [4, 5, 6]])

In [39]:
sample_array_matrix = np.array(([1,2,3,4], [5,6,7,8], [9,10,11,12], [13,14,15,16]))
sample_array_matrix

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [46]:
sample_array_matrix[2:,(1,2,3)]


array([[10, 11, 12],
       [14, 15, 16]])

In [49]:
sample_array_matrix[3:,]

array([[13, 14, 15, 16]])

In [51]:
bool = sample_array_matrix < 10
sample_array_matrix[bool]


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [55]:
a = 5
sample_array_matrix [sample_array_matrix <= a]


array([1, 2, 3, 4, 5])

In [56]:
sample_array = np.random.randn(6,6)
sample_array

array([[-0.56150815, -1.01212796, -0.67019027, -0.17897437,  0.00629602,
        -1.57866194],
       [-0.9340876 ,  0.19843379, -0.09009088,  0.40315874,  0.07153772,
        -0.01318021],
       [ 0.7517857 ,  1.45446594,  0.9715328 , -1.24237282,  1.78390108,
         0.65646619],
       [-0.3236018 , -2.31735651,  2.13763832, -1.31705237, -2.07640009,
         1.26125264],
       [-0.50257397,  0.32956889,  1.48153111,  1.49163165, -0.6083346 ,
         0.83194385],
       [ 0.28574945,  1.62403195,  1.65840137,  1.67414237, -0.56702496,
         0.48721302]])

In [57]:
sample_array.round()

array([[-1., -1., -1., -0.,  0., -2.],
       [-1.,  0., -0.,  0.,  0., -0.],
       [ 1.,  1.,  1., -1.,  2.,  1.],
       [-0., -2.,  2., -1., -2.,  1.],
       [-1.,  0.,  1.,  1., -1.,  1.],
       [ 0.,  2.,  2.,  2., -1.,  0.]])

In [61]:
np.round(sample_array, decimals = 2)

array([[-0.56, -1.01, -0.67, -0.18,  0.01, -1.58],
       [-0.93,  0.2 , -0.09,  0.4 ,  0.07, -0.01],
       [ 0.75,  1.45,  0.97, -1.24,  1.78,  0.66],
       [-0.32, -2.32,  2.14, -1.32, -2.08,  1.26],
       [-0.5 ,  0.33,  1.48,  1.49, -0.61,  0.83],
       [ 0.29,  1.62,  1.66,  1.67, -0.57,  0.49]])

In [62]:
strings_array = np.array (['cric', 'football', 'fooseball', 'cric', 'cric', 'football'])
np.unique(strings_array)

array(['cric', 'fooseball', 'football'], dtype='<U9')

In [64]:
sports = np.array ([['cric', 1], ['foo', 2], ['base', 3], ['badi', 4]])
sports

array([['cric', '1'],
       ['foo', '2'],
       ['base', '3'],
       ['badi', '4']], dtype='<U4')

In [66]:
sports[1,1]

'2'

In [71]:
array = np.random.randn(3,4)
array

array([[-0.51728845, -1.35580097, -0.54189209, -0.58439532],
       [ 0.8386038 , -1.52292829, -0.27244654, -0.47650661],
       [-1.76590903, -0.27736872,  1.26446348,  1.75665247]])

In [76]:
print type(type(int))

SyntaxError: invalid syntax (<ipython-input-76-edffc9f77013>, line 1)

In [77]:
9/2

4.5

In [78]:
9//2

4

In [79]:
~~~~~~5

5

In [82]:
s = 'Welcome'
print (s[0])
print s.lower()

SyntaxError: invalid syntax (<ipython-input-82-a13b4c7f0c5c>, line 3)

In [85]:
1*3**3

27

In [86]:
print '{0:.2}'.format(1.0 / 3)

SyntaxError: invalid syntax (<ipython-input-86-b7f88b62472d>, line 1)

In [87]:
print 'cd'.partition('cd')


SyntaxError: invalid syntax (<ipython-input-87-64daf11948d5>, line 1)